config/routes.rb
Rails.application.routes.draw do
  get 'personal_informations/index'
  get 'create_accounts/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'cellphones', to: 'users/registrations#new_cellphone'
    post 'cellphones', to: 'users/registrations#create_cellphone'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'cards', to: 'users/registrations#new_card'
    post 'cards', to: 'users/registrations#create_card'
  end
  root to: "items#index"
  resources :items
  resources :users, only: [:index, :show]
  resources :categorized_items, only: [:index]
  resources :branded_items, only: [:index]
  resources :credit_cards, only: [:index,:new,:show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end
  resources :create_accounts, only: [:index]
  resources :myinfomations, only: [:index]
  resources :notifications, only: [:index]
  resources :todos, only: [:index]
  resources :likes, only: [:index]
  resources :products, only: [:index, :new, :show, :edit, :update]
  resources :trading_products, only: [:index]
  resources :sold_products, only: [:index]
  resources :trading_items, only: [:index]
  resources :bought_items, only: [:index]
  resources :news, only: [:index]
  resources :reviews, only: [:index]
  resources :guides, only: [:index]
  resources :supports, only: [:index]
  resources :sales, only: [:index]
  resources :points, only: [:index]
  resources :profiles, only: [:edit]
  resources :orders, only: [:new] do
    member do
      get 'new', to: 'orders#new'
      post 'pay', to: 'orders#pay'
      get 'done', to: 'orders#done'
    end
  end
  resources :products, only: [:new, :create, :show, :edit, :update, :delete]
end

app/controllers/myinfomations_controller.rb
class MyinfomationsController < ApplicationController
  def index
  end
end

app/helpers/myinfomations_helper.rb
module MyinfomationsHelper
end

app/views/myinfomations/_sidebar.html.haml
.sidebar
  %nav.side__bar
    %ul.side__bar__list
      = link_to myinfomations_path do
        %li.side__bar__list__item
          マイページ
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to notifications_path do
        %li.side__bar__list__item
          お知らせ
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to todos_path do
        %li.side__bar__list__item
          やることリスト
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to likes_path do
        %li.side__bar__list__item
          いいね!一覧
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to new_product_path do
        %li.side__bar__list__item
          出品する
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to products_path do
        %li.side__bar__list__item
          出品した商品-出品中
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to trading_products_path do
        %li.side__bar__list__item
          出品した商品-取引中
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to sold_products_path do
        %li.side__bar__list__item
          出品した商品-売却済み
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to trading_items_path do
        %li.side__bar__list__item
          購入した商品-取引中
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to bought_items_path do
        %li.side__bar__list__item
          購入した商品-過去の取引
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to news_index_path do
        %li.side__bar__list__item
          ニュース一覧
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to reviews_path do
        %li.side__bar__list__item
          評価一覧
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to guides_path do
        %li.side__bar__list__item
          ガイド
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to supports_path do
        %li.side__bar__list__item
          お問い合わせ
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
    %h1.side__bar__list__head
      メルペイ
    %ul.side__bar__list
      = link_to sales_path do
        %li.side__bar__list__item
          売上・振込申請
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to points_path do
        %li.side__bar__list__item
          ポイント
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
    %h1.side__bar__list__head
      設定
    %ul.side__bar__list
      = link_to edit_profile_path(current_user) do
        %li.side__bar__list__item
          プロフィール
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to "#" do
        %li.side__bar__list__item
          発送元・お届け先住所変更
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to credit_cards_path do
        %li.side__bar__list__item
          支払い方法
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to "#" do
        %li.side__bar__list__item
          メール/パスワード
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to personal_informations_index_path do
        %li.side__bar__list__item
          本人情報
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to "#" do
        %li.side__bar__list__item
          電話番号の確認
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")
      = link_to user_path(current_user) do
        %li.side__bar__list__item
          ログアウト
          = icon('fas', 'chevron-right',class:"side__bar__list__item--icon")

app/views/myinfomations/index.html.haml
.header
  = render 'items/header'

- breadcrumb :myinfomations
= render partial: "layouts/breadcrumb"

.main
  .sidebar
    =render "sidebar"

  .myinfomations
    .head
      = link_to "#" do
        .inner
          =image_tag 'member_photo_noimage_thumb.png', class: 'inner__image'
          .inner__name
            %h2 *** ***
          .inner__data
            %span 評価 0
            %span 出品数 0
              
      =image_tag 'user-bg-07a3d1eec321479f465363323ddeb262.jpg', class: 'head__backImage'

    .tabs
      %ul.tabs__label
        %li.tabs__label.active
          %h3 お知らせ
        %li.tabs__label
          %h3 やることリスト

      .tab
        %ul.notifications.view
          =link_to "#" do
            %li
              =image_tag "square_red_logo.svg",class:"image"
              .notifications__text
                %label お知らせ１
              .notifications__time
                %span=icon('far', 'clock',class:"time--icon")
                %span 2 時間前
                = icon('fas', 'chevron-right',class:"right--icon")

          %li.all
            =link_to notifications_path do
              一覧を見る

        %ul.todos
          =link_to "#" do
            %li
              =image_tag "square_red_logo.svg",class:"image"
              .todos__text
                %label やることリスト１
              .todos__time
                %span=icon('far', 'clock',class:"time--icon")
                %span 2 時間前
                = icon('fas', 'chevron-right',class:"right--icon")
          
          %li.all
            =link_to todos_path do
              一覧を見る

    .trades
      %h4 購入した商品
      %ul.trades__label
        %li.trades__label.active
          %h3 取引中
        %li.trades__label
          %h3 過去の取引

      .trade
        %ul.tradingItems.view
          =link_to "#" do
            %li
              =image_tag "square_red_logo.svg",class:"image"
              .tradingItems__text
                %label 取引中１
              .tradingItems__time
                %span=icon('far', 'clock',class:"time--icon")
                %span 3 時間前
                = icon('fas', 'chevron-right',class:"right--icon")
              
          %li.all
            =link_to trading_items_path do
              一覧を見る

        %ul.boughtItems
          =link_to "#" do
            %li
              =image_tag "square_red_logo.svg",class:"image"
              .boughtItems__text
                %label 過去の取引１
              .boughtItems__time
                %span=icon('far', 'clock',class:"time--icon")
                %span 3 時間前
                = icon('fas', 'chevron-right',class:"right--icon")

          %li.all
            =link_to bought_items_path do
              一覧を見る

.footer
  = render 'items/footer'

.exhibition
  =link_to new_product_path, class: "exhibition__link" do
    出品
    = fas_icon 'camera', class: "exhibition__link__icon"