config/routes.rb
Rails.application.routes.draw do
  get 'personal_informations/index'
  get 'create_accounts/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'cellphones', to: 'users/registrations#new_cellphone'
    post 'cellphones', to: 'users/registrations#create_cellphone'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'cards', to: 'users/registrations#new_card'
    post 'cards', to: 'users/registrations#create_card'
  end
  root to: "items#index"
  resources :items
  resources :users, only: [:index, :show]
  resources :categorized_items, only: [:index]
  resources :branded_items, only: [:index]
  resources :credit_cards, only: [:index,:new,:show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end
  resources :create_accounts, only: [:index]
  resources :myinfomations, only: [:index]
  resources :notifications, only: [:index]
  resources :todos, only: [:index]
  resources :likes, only: [:index]
  resources :products, only: [:index, :new, :show, :edit, :update]
  resources :trading_products, only: [:index]
  resources :sold_products, only: [:index]
  resources :trading_items, only: [:index]
  resources :bought_items, only: [:index]
  resources :news, only: [:index]
  resources :reviews, only: [:index]
  resources :guides, only: [:index]
  resources :supports, only: [:index]
  resources :sales, only: [:index]
  resources :points, only: [:index]
  resources :profiles, only: [:edit]
  resources :orders, only: [:new] do
    member do
      get 'new', to: 'orders#new'
      post 'pay', to: 'orders#pay'
      get 'done', to: 'orders#done'
    end
  end
  resources :products, only: [:new, :create, :show, :edit, :update, :delete]
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  require "payjp"

  def index
  end

  def new # カード情報の追加
    cards = Card.where(user_id: current_user.id) #Cardモデルからログイン中ユーザの情報を変数cardに入れる。
    redirect_to action: "show" if cards.exists? #すでにcardが存在していればshowアクションへ飛ぶ。
  end

  def pay #payjpとCardのDBを作成
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"] #payjpと情報をやり取りするために秘密鍵をAPIキーに入れる。
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create( #Payjp::Customer.create：メールアドレスやIDなどを指定して顧客を作成するメソッド
        description: '登録テストです。', #なくてもいいがわかりやすいので。
        card: params['payjp-token'], #payjpでクレジットカードからトークンに変換されると、その情報はpayjp-tokenという名前でPOSTされる。
        metadata: {user_id: current_user.id} #なくてもいいがわかりやすいので。単なる説明文みたいなものです。
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card) #customer.idを自分たちのDBに保存することで、次回からカード情報を入力することなく、customer.idを指定して支払いできるようになる。default_cardはpayjpのレスポンスなので、ここでは定義していないが、payjpでは最初に情報入力したカードがdefault_cardになる。
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def show #DBのカード情報をpayjpに送り、customer情報を取り出す。
    @card = Card.find_by(user_id: current_user.id) #ログイン中ユーザの１番目のカードを取る。
    if @card.blank?
      redirect_to action: "new" #カードがなければnewへ
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id) #カードのcustomer情報をpayjpに送り、取り出した情報を変数customerに入れる。 Payjp::Customer.retrieve()：引数に指定したidで顧客情報を取得するメソッド。
      @default_card_information = customer.cards.retrieve(@card.card_id) #変数customerのカードのカードIDをデフォルトにする。default_card_informationはhamlで使います。
    end
  end

  def delete #payjpとCardのDBを削除
    card = Card.find_by(user_id: current_user.id)
    if card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: "new"
  end
end

app/controllers/creditcard_controller.rb
class CreditcardController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/index.html.haml
.header
  = render 'items/header'
  
- breadcrumb :credit_cards
= render partial: "layouts/breadcrumb"

.main
  .sidebar
    = render 'myinfomations/sidebar'

  .index
    .card
      .card__header
        %h1 
          支払い方法

      .card__content
        .card__content__list
          .card__content__list__name
            %h2
              クレジットカード一覧

          .card__content__list__add
            = link_to new_credit_card_path, class: "card__content__list__add__btn" do
              = icon('fas', 'credit-card',class:"card__content__list__add__btn--icon")
              クレジットカードを追加する

        .card__content__method
          = link_to "#", class: "card__content__method__btn" do
            支払い方法について
            = icon('fas', 'angle-right',class:"card__content__method__btn--icon")

.footer
  = render 'items/footer'

.exhibition
  =link_to new_product_path, class: "exhibition__link" do
    出品
    = fas_icon 'camera', class: "exhibition__link__icon"

app/views/credit_cards/new.html.haml
.header
  = render 'items/header'
- breadcrumb :credit_cards
= render partial: "layouts/breadcrumb"
.main
  .sidebar
    = render 'myinfomations/sidebar'
  .new
    .new__card
      = form_with url:pay_credit_cards_path, method: :post, html: { name: "CardForm" }, local:true do |f|
        .new__card__header
          %h1
            クレジットカード情報入力
        .new__card__create
          .new__card__create__formgroup
            .new__card__create__formgroup__number
              %label
                カード番号
              %span
                必須
              .new__card__create__formgroup__number__form
                = f.text_field "number", class:"new__card__create__formgroup__number__form__text", placeholder: "半角数字のみ",maxlength: "16", id: "card_number"
              .new__card__create__formgroup__number__image
                %li
                  = image_tag("https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Logo_Visa.svg/2000px-Logo_Visa.svg.png", alt: "visa", size: '45x17')
                %li
                  = image_tag("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mastercard-logo.svg/1280px-Mastercard-logo.svg.png", alt: "master", size: '25x20')
                %li
                  = image_tag("https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Saison_card_logo.svg/1024px-Saison_card_logo.svg.png", alt: "saison", size: '25x20')
                %li
                  = image_tag("https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/JCB_logo.svg/600px-JCB_logo.svg.png", alt: "jcb", size: '25x20')
                %li
                  = image_tag("https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/American_Express_logo_%282018%29.svg/1202px-American_Express_logo_%282018%29.svg.png", alt: "americanexpress", size: '25x20')
                %li
                  = image_tag("https://clipartart.com/images/diners-club-logo-clipart.png", alt: "dinersclub", size: '25x20')
                %li
                  = image_tag("https://blog.mudora.jp/wp-content/uploads/2013/11/disc_5121.png", alt: "discover", size: '30x25')
            .new__card__create__formgroup__validatedDate
              %label
                有効期限
              %span
                必須
              .new__card__create__formgroup__validatedDate__select
                .new__card__create__formgroup__validatedDate__select__month
                  %select.new__card__create__formgroup__validatedDate__select__month__box{id: "exp_month", name: "exp_month", type: "text"}
                    %option{value: "1"} 01
                    %option{value: "2"} 02
                    %option{value: "3"} 03
                    %option{value: "4"} 04
                    %option{value: "5"} 05
                    %option{value: "6"} 06
                    %option{value: "7"} 07
                    %option{value: "8"} 08
                    %option{value: "9"} 09
                    %option{value: "10"} 10
                    %option{value: "11"} 11
                    %option{value: "12"} 12
                  %label
                    月
                .new__card__create__formgroup__validatedDate__select__year
                  %select.new__card__create__formgroup__validatedDate__select__year__box{id: "exp_year", name: "exp_year", type: "text"}
                    %option{value: "2021"} 21
                    %option{value: "2022"} 22
                    %option{value: "2023"} 23
                    %option{value: "2024"} 24
                    %option{value: "2025"} 25
                    %option{value: "2026"} 26
                    %option{value: "2027"} 27
                    %option{value: "2028"} 28
                    %option{value: "2029"} 29
                    %option{value: "2030"} 30
                    %option{value: "2031"} 31
                  %label
                    年
            .new__card__create__formgroup__securityNumber
              %label
                セキュリティコード
              %span
                必須
              .new__card__create__formgroup__securityNumber__form
                = f.text_field "cvc", class:"new__card__create__formgroup__securityNumber__form__text", placeholder: "カード背面4桁もしくは3桁の番号",maxlength: "4", id: "cvc"
              .new__card__create__formgroup__securityNumber__question
                = icon('fas', 'question-circle',class:"new__card__create__formgroup__securityNumber__question--icon")
                カード裏面の番号とは？
              .new__card__create__formgroup__add
                = f.submit "追加する", id: "token", class: "new__card__create__formgroup__add__btn", name: "CardForm"
            #card_token
.footer
  = render 'items/footer'
.exhibition
  =link_to new_product_path, class: "exhibition__link" do
    出品
    = fas_icon 'camera', class: "exhibition__link__icon"

app/views/credit_cards/show.html.haml
.header
  = render 'items/header'

- breadcrumb :credit_cards
= render partial: "layouts/breadcrumb"

.main
  .sidebar
    = render 'myinfomations/sidebar'
    
  .show
    .card
      .card__header
        %h1
          支払い方法

      .card__content
        .card__content__list
          .card__content__list__name
            %h2
              クレジットカード一覧
              
          .card__content__list__register
            .card__content__list__register__image
              %li
                = image_tag("https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Logo_Visa.svg/2000px-Logo_Visa.svg.png", alt: "visa", size: '45x17')
          
            .card__content__list__register__number
              %li
                = "**** **** ****" + @default_card_information.last4
          
            .card__content__list__register__validatedDate
              %li
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
          
            .card__content__list__register__delete
              = form_with url:delete_credit_cards_path, method: :post, html: { name: "CardForm" }, local:true do |f|
                %input{ type: "hidden", name: "card_id", value: "" }
                %button{class: "card__content__list__register__delete__btn"} 削除する

        .card__content__method
          = link_to "#", class: "card__content__method__btn" do
            支払い方法について
            = icon('fas', 'angle-right',class:"card__content__method__btn--icon")

.footer
  = render 'items/footer'

.exhibition
  =link_to new_product_path, class: "exhibition__link" do
    出品
    = fas_icon 'camera', class: "exhibition__link__icon"